// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: engine.proto

package banyanpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	ApiAddress    string                 `protobuf:"bytes,2,opt,name=api_address,json=apiAddress,proto3" json:"api_address,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	WgPublicKey   string                 `protobuf:"bytes,5,opt,name=wg_public_key,json=wgPublicKey,proto3" json:"wg_public_key,omitempty"` // agent's WireGuard public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RegisterRequest) GetApiAddress() string {
	if x != nil {
		return x.ApiAddress
	}
	return ""
}

func (x *RegisterRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterRequest) GetWgPublicKey() string {
	if x != nil {
		return x.WgPublicKey
	}
	return ""
}

type RegisterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RegistryUrl     string                 `protobuf:"bytes,1,opt,name=registry_url,json=registryUrl,proto3" json:"registry_url,omitempty"`
	StoreEndpoints  []string               `protobuf:"bytes,2,rep,name=store_endpoints,json=storeEndpoints,proto3" json:"store_endpoints,omitempty"`    // DEPRECATED: was etcd endpoints for Flannel
	VpcCidr         string                 `protobuf:"bytes,3,opt,name=vpc_cidr,json=vpcCidr,proto3" json:"vpc_cidr,omitempty"`                         // VPC network CIDR (e.g., "10.0.0.0/16")
	AllocatedSubnet string                 `protobuf:"bytes,4,opt,name=allocated_subnet,json=allocatedSubnet,proto3" json:"allocated_subnet,omitempty"` // /24 subnet for this agent (e.g., "10.0.45.0/24")
	OverlayType     string                 `protobuf:"bytes,5,opt,name=overlay_type,json=overlayType,proto3" json:"overlay_type,omitempty"`             // "wireguard" or "vxlan"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetRegistryUrl() string {
	if x != nil {
		return x.RegistryUrl
	}
	return ""
}

func (x *RegisterResponse) GetStoreEndpoints() []string {
	if x != nil {
		return x.StoreEndpoints
	}
	return nil
}

func (x *RegisterResponse) GetVpcCidr() string {
	if x != nil {
		return x.VpcCidr
	}
	return ""
}

func (x *RegisterResponse) GetAllocatedSubnet() string {
	if x != nil {
		return x.AllocatedSubnet
	}
	return ""
}

func (x *RegisterResponse) GetOverlayType() string {
	if x != nil {
		return x.OverlayType
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *HeartbeatRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VpcPeers        []*VPCPeer             `protobuf:"bytes,1,rep,name=vpc_peers,json=vpcPeers,proto3" json:"vpc_peers,omitempty"`                      // all other agents' network info
	ServiceBackends []*ServiceBackend      `protobuf:"bytes,2,rep,name=service_backends,json=serviceBackends,proto3" json:"service_backends,omitempty"` // all service backends cluster-wide
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetVpcPeers() []*VPCPeer {
	if x != nil {
		return x.VpcPeers
	}
	return nil
}

func (x *HeartbeatResponse) GetServiceBackends() []*ServiceBackend {
	if x != nil {
		return x.ServiceBackends
	}
	return nil
}

type VPCPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnet        string                 `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`                        // peer's allocated subnet
	HostIp        string                 `protobuf:"bytes,2,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`          // peer's reachable IP
	VtepMac       string                 `protobuf:"bytes,3,opt,name=vtep_mac,json=vtepMac,proto3" json:"vtep_mac,omitempty"`       // deterministic VTEP MAC (VXLAN)
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // WireGuard public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPCPeer) Reset() {
	*x = VPCPeer{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPCPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPCPeer) ProtoMessage() {}

func (x *VPCPeer) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPCPeer.ProtoReflect.Descriptor instead.
func (*VPCPeer) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *VPCPeer) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *VPCPeer) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *VPCPeer) GetVtepMac() string {
	if x != nil {
		return x.VtepMac
	}
	return ""
}

func (x *VPCPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type PollTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTasksRequest) Reset() {
	*x = PollTasksRequest{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTasksRequest) ProtoMessage() {}

func (x *PollTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTasksRequest.ProtoReflect.Descriptor instead.
func (*PollTasksRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *PollTasksRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

type PollTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskRecord          `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTasksResponse) Reset() {
	*x = PollTasksResponse{}
	mi := &file_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTasksResponse) ProtoMessage() {}

func (x *PollTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTasksResponse.ProtoReflect.Descriptor instead.
func (*PollTasksResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *PollTasksResponse) GetTasks() []*TaskRecord {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ReportTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ContainerName string                 `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Result        *TaskResult            `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultRequest) Reset() {
	*x = ReportTaskResultRequest{}
	mi := &file_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultRequest) ProtoMessage() {}

func (x *ReportTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *ReportTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportTaskResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportTaskResultRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ReportTaskResultRequest) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResult) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type ReportTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultResponse) Reset() {
	*x = ReportTaskResultResponse{}
	mi := &file_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultResponse) ProtoMessage() {}

func (x *ReportTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{9}
}

type ReportContainerHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Containers    []*ContainerStatus     `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportContainerHealthRequest) Reset() {
	*x = ReportContainerHealthRequest{}
	mi := &file_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportContainerHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportContainerHealthRequest) ProtoMessage() {}

func (x *ReportContainerHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportContainerHealthRequest.ProtoReflect.Descriptor instead.
func (*ReportContainerHealthRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{10}
}

func (x *ReportContainerHealthRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *ReportContainerHealthRequest) GetContainers() []*ContainerStatus {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"` // container's overlay IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{11}
}

func (x *ContainerStatus) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerStatus) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ServiceBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ContainerIp   string                 `protobuf:"bytes,2,opt,name=container_ip,json=containerIp,proto3" json:"container_ip,omitempty"`
	Ports         []string               `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	AgentName     string                 `protobuf:"bytes,4,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceBackend) Reset() {
	*x = ServiceBackend{}
	mi := &file_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceBackend) ProtoMessage() {}

func (x *ServiceBackend) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceBackend.ProtoReflect.Descriptor instead.
func (*ServiceBackend) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceBackend) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ServiceBackend) GetContainerIp() string {
	if x != nil {
		return x.ContainerIp
	}
	return ""
}

func (x *ServiceBackend) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceBackend) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *ServiceBackend) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ReportContainerHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportContainerHealthResponse) Reset() {
	*x = ReportContainerHealthResponse{}
	mi := &file_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportContainerHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportContainerHealthResponse) ProtoMessage() {}

func (x *ReportContainerHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportContainerHealthResponse.ProtoReflect.Descriptor instead.
func (*ReportContainerHealthResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{13}
}

type TaskRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ReplicaIndex  int32                  `protobuf:"varint,4,opt,name=replica_index,json=replicaIndex,proto3" json:"replica_index,omitempty"`
	AgentId       string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Image         string                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	ContainerName string                 `protobuf:"bytes,9,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Ports         []string               `protobuf:"bytes,10,rep,name=ports,proto3" json:"ports,omitempty"`
	Environment   []string               `protobuf:"bytes,11,rep,name=environment,proto3" json:"environment,omitempty"`
	Command       []string               `protobuf:"bytes,12,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRecord) Reset() {
	*x = TaskRecord{}
	mi := &file_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRecord) ProtoMessage() {}

func (x *TaskRecord) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRecord.ProtoReflect.Descriptor instead.
func (*TaskRecord) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{14}
}

func (x *TaskRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskRecord) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *TaskRecord) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TaskRecord) GetReplicaIndex() int32 {
	if x != nil {
		return x.ReplicaIndex
	}
	return 0
}

func (x *TaskRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskRecord) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TaskRecord) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *TaskRecord) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *TaskRecord) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *TaskRecord) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type DeployRPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Services      []string               `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"` // optional: deploy only these services
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`         // optional: deployment tags for agent matching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRPCRequest) Reset() {
	*x = DeployRPCRequest{}
	mi := &file_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRPCRequest) ProtoMessage() {}

func (x *DeployRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRPCRequest.ProtoReflect.Descriptor instead.
func (*DeployRPCRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{15}
}

func (x *DeployRPCRequest) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *DeployRPCRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *DeployRPCRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeployRPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRPCResponse) Reset() {
	*x = DeployRPCResponse{}
	mi := &file_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRPCResponse) ProtoMessage() {}

func (x *DeployRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRPCResponse.ProtoReflect.Descriptor instead.
func (*DeployRPCResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{16}
}

func (x *DeployRPCResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployRPCResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Manifest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Name          string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                      `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Services      map[string]*ManifestService `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{17}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetServices() map[string]*ManifestService {
	if x != nil {
		return x.Services
	}
	return nil
}

type ManifestService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Build         *ManifestBuild         `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	Deploy        *ManifestDeploy        `protobuf:"bytes,3,opt,name=deploy,proto3" json:"deploy,omitempty"`
	Ports         []string               `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	Environment   []string               `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty"`
	Command       []string               `protobuf:"bytes,6,rep,name=command,proto3" json:"command,omitempty"`
	DependsOn     []string               `protobuf:"bytes,7,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestService) Reset() {
	*x = ManifestService{}
	mi := &file_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestService) ProtoMessage() {}

func (x *ManifestService) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestService.ProtoReflect.Descriptor instead.
func (*ManifestService) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{18}
}

func (x *ManifestService) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ManifestService) GetBuild() *ManifestBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *ManifestService) GetDeploy() *ManifestDeploy {
	if x != nil {
		return x.Deploy
	}
	return nil
}

func (x *ManifestService) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ManifestService) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ManifestService) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ManifestService) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

type ManifestBuild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Dockerfile    string                 `protobuf:"bytes,2,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestBuild) Reset() {
	*x = ManifestBuild{}
	mi := &file_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestBuild) ProtoMessage() {}

func (x *ManifestBuild) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestBuild.ProtoReflect.Descriptor instead.
func (*ManifestBuild) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{19}
}

func (x *ManifestBuild) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ManifestBuild) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

type ManifestDeploy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      int32                  `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Placement     *ManifestPlacement     `protobuf:"bytes,2,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestDeploy) Reset() {
	*x = ManifestDeploy{}
	mi := &file_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestDeploy) ProtoMessage() {}

func (x *ManifestDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestDeploy.ProtoReflect.Descriptor instead.
func (*ManifestDeploy) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{20}
}

func (x *ManifestDeploy) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ManifestDeploy) GetPlacement() *ManifestPlacement {
	if x != nil {
		return x.Placement
	}
	return nil
}

type ManifestPlacement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestPlacement) Reset() {
	*x = ManifestPlacement{}
	mi := &file_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestPlacement) ProtoMessage() {}

func (x *ManifestPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestPlacement.ProtoReflect.Descriptor instead.
func (*ManifestPlacement) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{21}
}

func (x *ManifestPlacement) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type DownRPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Services      []string               `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownRPCRequest) Reset() {
	*x = DownRPCRequest{}
	mi := &file_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownRPCRequest) ProtoMessage() {}

func (x *DownRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownRPCRequest.ProtoReflect.Descriptor instead.
func (*DownRPCRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{22}
}

func (x *DownRPCRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DownRPCRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *DownRPCRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DownRPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskCount     int32                  `protobuf:"varint,1,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownRPCResponse) Reset() {
	*x = DownRPCResponse{}
	mi := &file_engine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownRPCResponse) ProtoMessage() {}

func (x *DownRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownRPCResponse.ProtoReflect.Descriptor instead.
func (*DownRPCResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{23}
}

func (x *DownRPCResponse) GetTaskCount() int32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_engine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{24}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Deployments   []*DeploymentInfo      `protobuf:"bytes,2,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_engine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{25}
}

func (x *GetStatusResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *GetStatusResponse) GetDeployments() []*DeploymentInfo {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ApiAddress    string                 `protobuf:"bytes,3,opt,name=api_address,json=apiAddress,proto3" json:"api_address,omitempty"`
	LastSeenUnix  int64                  `protobuf:"varint,4,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_engine_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{26}
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentInfo) GetApiAddress() string {
	if x != nil {
		return x.ApiAddress
	}
	return ""
}

func (x *AgentInfo) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *AgentInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *AgentInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeploymentInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Services      map[string]*ServiceInfo `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAtUnix int64                   `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                   `protobuf:"varint,6,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	Error         string                  `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Tasks         []*TaskInfo             `protobuf:"bytes,8,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Healthy       int32                   `protobuf:"varint,9,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Total         int32                   `protobuf:"varint,10,opt,name=total,proto3" json:"total,omitempty"`
	Tags          []string                `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentInfo) Reset() {
	*x = DeploymentInfo{}
	mi := &file_engine_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentInfo) ProtoMessage() {}

func (x *DeploymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentInfo.ProtoReflect.Descriptor instead.
func (*DeploymentInfo) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{27}
}

func (x *DeploymentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeploymentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeploymentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeploymentInfo) GetServices() map[string]*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *DeploymentInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *DeploymentInfo) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *DeploymentInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeploymentInfo) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *DeploymentInfo) GetHealthy() int32 {
	if x != nil {
		return x.Healthy
	}
	return 0
}

func (x *DeploymentInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DeploymentInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Ports         []string               `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Environment   []string               `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty"`
	Command       []string               `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	DependsOn     []string               `protobuf:"bytes,6,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_engine_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{28}
}

func (x *ServiceInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ServiceInfo) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ServiceInfo) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceInfo) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ServiceInfo) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ServiceInfo) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

type TaskInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId           string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ServiceName            string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ReplicaIndex           int32                  `protobuf:"varint,4,opt,name=replica_index,json=replicaIndex,proto3" json:"replica_index,omitempty"`
	AgentId                string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type                   string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Status                 string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Image                  string                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	ContainerName          string                 `protobuf:"bytes,9,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Ports                  []string               `protobuf:"bytes,10,rep,name=ports,proto3" json:"ports,omitempty"`
	Environment            []string               `protobuf:"bytes,11,rep,name=environment,proto3" json:"environment,omitempty"`
	Command                []string               `protobuf:"bytes,12,rep,name=command,proto3" json:"command,omitempty"`
	ContainerStatus        string                 `protobuf:"bytes,13,opt,name=container_status,json=containerStatus,proto3" json:"container_status,omitempty"`
	ContainerCheckedAtUnix int64                  `protobuf:"varint,14,opt,name=container_checked_at_unix,json=containerCheckedAtUnix,proto3" json:"container_checked_at_unix,omitempty"`
	CreatedAtUnix          int64                  `protobuf:"varint,15,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix          int64                  `protobuf:"varint,16,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	Error                  string                 `protobuf:"bytes,17,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_engine_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{29}
}

func (x *TaskInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskInfo) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *TaskInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TaskInfo) GetReplicaIndex() int32 {
	if x != nil {
		return x.ReplicaIndex
	}
	return 0
}

func (x *TaskInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TaskInfo) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *TaskInfo) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *TaskInfo) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *TaskInfo) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TaskInfo) GetContainerStatus() string {
	if x != nil {
		return x.ContainerStatus
	}
	return ""
}

func (x *TaskInfo) GetContainerCheckedAtUnix() int64 {
	if x != nil {
		return x.ContainerCheckedAtUnix
	}
	return 0
}

func (x *TaskInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *TaskInfo) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *TaskInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          int32                  `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_engine_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{30}
}

func (x *GetLogsRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *GetLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *GetLogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_engine_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{31}
}

func (x *GetLogsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_engine_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{32}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegistryUrl   string                 `protobuf:"bytes,1,opt,name=registry_url,json=registryUrl,proto3" json:"registry_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_engine_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{33}
}

func (x *GetInfoResponse) GetRegistryUrl() string {
	if x != nil {
		return x.RegistryUrl
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_engine_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{34}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_engine_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{35}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\tbanyan.v1\"\xae\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1f\n" +
	"\vapi_address\x18\x02 \x01(\tR\n" +
	"apiAddress\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\"\n" +
	"\rwg_public_key\x18\x05 \x01(\tR\vwgPublicKey\"\xc7\x01\n" +
	"\x10RegisterResponse\x12!\n" +
	"\fregistry_url\x18\x01 \x01(\tR\vregistryUrl\x12'\n" +
	"\x0fstore_endpoints\x18\x02 \x03(\tR\x0estoreEndpoints\x12\x19\n" +
	"\bvpc_cidr\x18\x03 \x01(\tR\avpcCidr\x12)\n" +
	"\x10allocated_subnet\x18\x04 \x01(\tR\x0fallocatedSubnet\x12!\n" +
	"\foverlay_type\x18\x05 \x01(\tR\voverlayType\"j\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\x8a\x01\n" +
	"\x11HeartbeatResponse\x12/\n" +
	"\tvpc_peers\x18\x01 \x03(\v2\x12.banyan.v1.VPCPeerR\bvpcPeers\x12D\n" +
	"\x10service_backends\x18\x02 \x03(\v2\x19.banyan.v1.ServiceBackendR\x0fserviceBackends\"t\n" +
	"\aVPCPeer\x12\x16\n" +
	"\x06subnet\x18\x01 \x01(\tR\x06subnet\x12\x17\n" +
	"\ahost_ip\x18\x02 \x01(\tR\x06hostIp\x12\x19\n" +
	"\bvtep_mac\x18\x03 \x01(\tR\avtepMac\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\"1\n" +
	"\x10PollTasksRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\"@\n" +
	"\x11PollTasksResponse\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.banyan.v1.TaskRecordR\x05tasks\"\xd1\x01\n" +
	"\x17ReportTaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12-\n" +
	"\x06result\x18\x06 \x01(\v2\x15.banyan.v1.TaskResultR\x06result\"/\n" +
	"\n" +
	"TaskResult\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\x1a\n" +
	"\x18ReportTaskResultResponse\"y\n" +
	"\x1cReportContainerHealthRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12:\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2\x1a.banyan.v1.ContainerStatusR\n" +
	"containers\"`\n" +
	"\x0fContainerStatus\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"\xb2\x01\n" +
	"\x0eServiceBackend\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12!\n" +
	"\fcontainer_ip\x18\x02 \x01(\tR\vcontainerIp\x12\x14\n" +
	"\x05ports\x18\x03 \x03(\tR\x05ports\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x04 \x01(\tR\tagentName\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\"\x1f\n" +
	"\x1dReportContainerHealthResponse\"\xdf\x02\n" +
	"\n" +
	"TaskRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12#\n" +
	"\rreplica_index\x18\x04 \x01(\x05R\freplicaIndex\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\x12%\n" +
	"\x0econtainer_name\x18\t \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05ports\x18\n" +
	" \x03(\tR\x05ports\x12 \n" +
	"\venvironment\x18\v \x03(\tR\venvironment\x12\x18\n" +
	"\acommand\x18\f \x03(\tR\acommand\"s\n" +
	"\x10DeployRPCRequest\x12/\n" +
	"\bmanifest\x18\x01 \x01(\v2\x13.banyan.v1.ManifestR\bmanifest\x12\x1a\n" +
	"\bservices\x18\x02 \x03(\tR\bservices\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"P\n" +
	"\x11DeployRPCResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xd0\x01\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12=\n" +
	"\bservices\x18\x03 \x03(\v2!.banyan.v1.Manifest.ServicesEntryR\bservices\x1aW\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.banyan.v1.ManifestServiceR\x05value:\x028\x01\"\xfb\x01\n" +
	"\x0fManifestService\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12.\n" +
	"\x05build\x18\x02 \x01(\v2\x18.banyan.v1.ManifestBuildR\x05build\x121\n" +
	"\x06deploy\x18\x03 \x01(\v2\x19.banyan.v1.ManifestDeployR\x06deploy\x12\x14\n" +
	"\x05ports\x18\x04 \x03(\tR\x05ports\x12 \n" +
	"\venvironment\x18\x05 \x03(\tR\venvironment\x12\x18\n" +
	"\acommand\x18\x06 \x03(\tR\acommand\x12\x1d\n" +
	"\n" +
	"depends_on\x18\a \x03(\tR\tdependsOn\"I\n" +
	"\rManifestBuild\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\x02 \x01(\tR\n" +
	"dockerfile\"h\n" +
	"\x0eManifestDeploy\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x12:\n" +
	"\tplacement\x18\x02 \x01(\v2\x1c.banyan.v1.ManifestPlacementR\tplacement\"'\n" +
	"\x11ManifestPlacement\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\"T\n" +
	"\x0eDownRPCRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bservices\x18\x02 \x03(\tR\bservices\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"0\n" +
	"\x0fDownRPCResponse\x12\x1d\n" +
	"\n" +
	"task_count\x18\x01 \x01(\x05R\ttaskCount\"\x12\n" +
	"\x10GetStatusRequest\"~\n" +
	"\x11GetStatusResponse\x12,\n" +
	"\x06agents\x18\x01 \x03(\v2\x14.banyan.v1.AgentInfoR\x06agents\x12;\n" +
	"\vdeployments\x18\x02 \x03(\v2\x19.banyan.v1.DeploymentInfoR\vdeployments\"\xba\x01\n" +
	"\tAgentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vapi_address\x18\x03 \x01(\tR\n" +
	"apiAddress\x12$\n" +
	"\x0elast_seen_unix\x18\x04 \x01(\x03R\flastSeenUnix\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"\xbb\x03\n" +
	"\x0eDeploymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12C\n" +
	"\bservices\x18\x04 \x03(\v2'.banyan.v1.DeploymentInfo.ServicesEntryR\bservices\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x06 \x01(\x03R\rupdatedAtUnix\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12)\n" +
	"\x05tasks\x18\b \x03(\v2\x13.banyan.v1.TaskInfoR\x05tasks\x12\x18\n" +
	"\ahealthy\x18\t \x01(\x05R\ahealthy\x12\x14\n" +
	"\x05total\x18\n" +
	" \x01(\x05R\x05total\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x1aS\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.banyan.v1.ServiceInfoR\x05value:\x028\x01\"\xb0\x01\n" +
	"\vServiceInfo\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\x12\x14\n" +
	"\x05ports\x18\x03 \x03(\tR\x05ports\x12 \n" +
	"\venvironment\x18\x04 \x03(\tR\venvironment\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x06 \x03(\tR\tdependsOn\"\xa9\x04\n" +
	"\bTaskInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12#\n" +
	"\rreplica_index\x18\x04 \x01(\x05R\freplicaIndex\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\x12%\n" +
	"\x0econtainer_name\x18\t \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05ports\x18\n" +
	" \x03(\tR\x05ports\x12 \n" +
	"\venvironment\x18\v \x03(\tR\venvironment\x12\x18\n" +
	"\acommand\x18\f \x03(\tR\acommand\x12)\n" +
	"\x10container_status\x18\r \x01(\tR\x0fcontainerStatus\x129\n" +
	"\x19container_checked_at_unix\x18\x0e \x01(\x03R\x16containerCheckedAtUnix\x12&\n" +
	"\x0fcreated_at_unix\x18\x0f \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x10 \x01(\x03R\rupdatedAtUnix\x12\x14\n" +
	"\x05error\x18\x11 \x01(\tR\x05error\"c\n" +
	"\x0eGetLogsRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x12\n" +
	"\x04tail\x18\x03 \x01(\x05R\x04tail\"%\n" +
	"\x0fGetLogsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x10\n" +
	"\x0eGetInfoRequest\"4\n" +
	"\x0fGetInfoResponse\x12!\n" +
	"\fregistry_url\x18\x01 \x01(\tR\vregistryUrl\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xbe\x06\n" +
	"\rEngineService\x12C\n" +
	"\bRegister\x12\x1a.banyan.v1.RegisterRequest\x1a\x1b.banyan.v1.RegisterResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.banyan.v1.HeartbeatRequest\x1a\x1c.banyan.v1.HeartbeatResponse\x12F\n" +
	"\tPollTasks\x12\x1b.banyan.v1.PollTasksRequest\x1a\x1c.banyan.v1.PollTasksResponse\x12[\n" +
	"\x10ReportTaskResult\x12\".banyan.v1.ReportTaskResultRequest\x1a#.banyan.v1.ReportTaskResultResponse\x12j\n" +
	"\x15ReportContainerHealth\x12'.banyan.v1.ReportContainerHealthRequest\x1a(.banyan.v1.ReportContainerHealthResponse\x12C\n" +
	"\x06Deploy\x12\x1b.banyan.v1.DeployRPCRequest\x1a\x1c.banyan.v1.DeployRPCResponse\x12=\n" +
	"\x04Down\x12\x19.banyan.v1.DownRPCRequest\x1a\x1a.banyan.v1.DownRPCResponse\x12F\n" +
	"\tGetStatus\x12\x1b.banyan.v1.GetStatusRequest\x1a\x1c.banyan.v1.GetStatusResponse\x12B\n" +
	"\aGetLogs\x12\x19.banyan.v1.GetLogsRequest\x1a\x1a.banyan.v1.GetLogsResponse0\x01\x12@\n" +
	"\aGetInfo\x12\x19.banyan.v1.GetInfoRequest\x1a\x1a.banyan.v1.GetInfoResponse\x12=\n" +
	"\x06Health\x12\x18.banyan.v1.HealthRequest\x1a\x19.banyan.v1.HealthResponseB0Z.github.com/fertile-org/banyan/pkg/rpc/banyanpbb\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_engine_proto_goTypes = []any{
	(*RegisterRequest)(nil),               // 0: banyan.v1.RegisterRequest
	(*RegisterResponse)(nil),              // 1: banyan.v1.RegisterResponse
	(*HeartbeatRequest)(nil),              // 2: banyan.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),             // 3: banyan.v1.HeartbeatResponse
	(*VPCPeer)(nil),                       // 4: banyan.v1.VPCPeer
	(*PollTasksRequest)(nil),              // 5: banyan.v1.PollTasksRequest
	(*PollTasksResponse)(nil),             // 6: banyan.v1.PollTasksResponse
	(*ReportTaskResultRequest)(nil),       // 7: banyan.v1.ReportTaskResultRequest
	(*TaskResult)(nil),                    // 8: banyan.v1.TaskResult
	(*ReportTaskResultResponse)(nil),      // 9: banyan.v1.ReportTaskResultResponse
	(*ReportContainerHealthRequest)(nil),  // 10: banyan.v1.ReportContainerHealthRequest
	(*ContainerStatus)(nil),               // 11: banyan.v1.ContainerStatus
	(*ServiceBackend)(nil),                // 12: banyan.v1.ServiceBackend
	(*ReportContainerHealthResponse)(nil), // 13: banyan.v1.ReportContainerHealthResponse
	(*TaskRecord)(nil),                    // 14: banyan.v1.TaskRecord
	(*DeployRPCRequest)(nil),              // 15: banyan.v1.DeployRPCRequest
	(*DeployRPCResponse)(nil),             // 16: banyan.v1.DeployRPCResponse
	(*Manifest)(nil),                      // 17: banyan.v1.Manifest
	(*ManifestService)(nil),               // 18: banyan.v1.ManifestService
	(*ManifestBuild)(nil),                 // 19: banyan.v1.ManifestBuild
	(*ManifestDeploy)(nil),                // 20: banyan.v1.ManifestDeploy
	(*ManifestPlacement)(nil),             // 21: banyan.v1.ManifestPlacement
	(*DownRPCRequest)(nil),                // 22: banyan.v1.DownRPCRequest
	(*DownRPCResponse)(nil),               // 23: banyan.v1.DownRPCResponse
	(*GetStatusRequest)(nil),              // 24: banyan.v1.GetStatusRequest
	(*GetStatusResponse)(nil),             // 25: banyan.v1.GetStatusResponse
	(*AgentInfo)(nil),                     // 26: banyan.v1.AgentInfo
	(*DeploymentInfo)(nil),                // 27: banyan.v1.DeploymentInfo
	(*ServiceInfo)(nil),                   // 28: banyan.v1.ServiceInfo
	(*TaskInfo)(nil),                      // 29: banyan.v1.TaskInfo
	(*GetLogsRequest)(nil),                // 30: banyan.v1.GetLogsRequest
	(*GetLogsResponse)(nil),               // 31: banyan.v1.GetLogsResponse
	(*GetInfoRequest)(nil),                // 32: banyan.v1.GetInfoRequest
	(*GetInfoResponse)(nil),               // 33: banyan.v1.GetInfoResponse
	(*HealthRequest)(nil),                 // 34: banyan.v1.HealthRequest
	(*HealthResponse)(nil),                // 35: banyan.v1.HealthResponse
	nil,                                   // 36: banyan.v1.Manifest.ServicesEntry
	nil,                                   // 37: banyan.v1.DeploymentInfo.ServicesEntry
}
var file_engine_proto_depIdxs = []int32{
	4,  // 0: banyan.v1.HeartbeatResponse.vpc_peers:type_name -> banyan.v1.VPCPeer
	12, // 1: banyan.v1.HeartbeatResponse.service_backends:type_name -> banyan.v1.ServiceBackend
	14, // 2: banyan.v1.PollTasksResponse.tasks:type_name -> banyan.v1.TaskRecord
	8,  // 3: banyan.v1.ReportTaskResultRequest.result:type_name -> banyan.v1.TaskResult
	11, // 4: banyan.v1.ReportContainerHealthRequest.containers:type_name -> banyan.v1.ContainerStatus
	17, // 5: banyan.v1.DeployRPCRequest.manifest:type_name -> banyan.v1.Manifest
	36, // 6: banyan.v1.Manifest.services:type_name -> banyan.v1.Manifest.ServicesEntry
	19, // 7: banyan.v1.ManifestService.build:type_name -> banyan.v1.ManifestBuild
	20, // 8: banyan.v1.ManifestService.deploy:type_name -> banyan.v1.ManifestDeploy
	21, // 9: banyan.v1.ManifestDeploy.placement:type_name -> banyan.v1.ManifestPlacement
	26, // 10: banyan.v1.GetStatusResponse.agents:type_name -> banyan.v1.AgentInfo
	27, // 11: banyan.v1.GetStatusResponse.deployments:type_name -> banyan.v1.DeploymentInfo
	37, // 12: banyan.v1.DeploymentInfo.services:type_name -> banyan.v1.DeploymentInfo.ServicesEntry
	29, // 13: banyan.v1.DeploymentInfo.tasks:type_name -> banyan.v1.TaskInfo
	18, // 14: banyan.v1.Manifest.ServicesEntry.value:type_name -> banyan.v1.ManifestService
	28, // 15: banyan.v1.DeploymentInfo.ServicesEntry.value:type_name -> banyan.v1.ServiceInfo
	0,  // 16: banyan.v1.EngineService.Register:input_type -> banyan.v1.RegisterRequest
	2,  // 17: banyan.v1.EngineService.Heartbeat:input_type -> banyan.v1.HeartbeatRequest
	5,  // 18: banyan.v1.EngineService.PollTasks:input_type -> banyan.v1.PollTasksRequest
	7,  // 19: banyan.v1.EngineService.ReportTaskResult:input_type -> banyan.v1.ReportTaskResultRequest
	10, // 20: banyan.v1.EngineService.ReportContainerHealth:input_type -> banyan.v1.ReportContainerHealthRequest
	15, // 21: banyan.v1.EngineService.Deploy:input_type -> banyan.v1.DeployRPCRequest
	22, // 22: banyan.v1.EngineService.Down:input_type -> banyan.v1.DownRPCRequest
	24, // 23: banyan.v1.EngineService.GetStatus:input_type -> banyan.v1.GetStatusRequest
	30, // 24: banyan.v1.EngineService.GetLogs:input_type -> banyan.v1.GetLogsRequest
	32, // 25: banyan.v1.EngineService.GetInfo:input_type -> banyan.v1.GetInfoRequest
	34, // 26: banyan.v1.EngineService.Health:input_type -> banyan.v1.HealthRequest
	1,  // 27: banyan.v1.EngineService.Register:output_type -> banyan.v1.RegisterResponse
	3,  // 28: banyan.v1.EngineService.Heartbeat:output_type -> banyan.v1.HeartbeatResponse
	6,  // 29: banyan.v1.EngineService.PollTasks:output_type -> banyan.v1.PollTasksResponse
	9,  // 30: banyan.v1.EngineService.ReportTaskResult:output_type -> banyan.v1.ReportTaskResultResponse
	13, // 31: banyan.v1.EngineService.ReportContainerHealth:output_type -> banyan.v1.ReportContainerHealthResponse
	16, // 32: banyan.v1.EngineService.Deploy:output_type -> banyan.v1.DeployRPCResponse
	23, // 33: banyan.v1.EngineService.Down:output_type -> banyan.v1.DownRPCResponse
	25, // 34: banyan.v1.EngineService.GetStatus:output_type -> banyan.v1.GetStatusResponse
	31, // 35: banyan.v1.EngineService.GetLogs:output_type -> banyan.v1.GetLogsResponse
	33, // 36: banyan.v1.EngineService.GetInfo:output_type -> banyan.v1.GetInfoResponse
	35, // 37: banyan.v1.EngineService.Health:output_type -> banyan.v1.HealthResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
