// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent.proto

package banyanpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	banyanpb "github.com/fertile-org/banyan/pkg/rpc/banyanpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "banyan.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceStreamLogsProcedure is the fully-qualified name of the AgentService's StreamLogs RPC.
	AgentServiceStreamLogsProcedure = "/banyan.v1.AgentService/StreamLogs"
)

// AgentServiceClient is a client for the banyan.v1.AgentService service.
type AgentServiceClient interface {
	StreamLogs(context.Context, *connect.Request[banyanpb.StreamLogsRequest]) (*connect.ServerStreamForClient[banyanpb.StreamLogsResponse], error)
}

// NewAgentServiceClient constructs a client for the banyan.v1.AgentService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := banyanpb.File_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		streamLogs: connect.NewClient[banyanpb.StreamLogsRequest, banyanpb.StreamLogsResponse](
			httpClient,
			baseURL+AgentServiceStreamLogsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StreamLogs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	streamLogs *connect.Client[banyanpb.StreamLogsRequest, banyanpb.StreamLogsResponse]
}

// StreamLogs calls banyan.v1.AgentService.StreamLogs.
func (c *agentServiceClient) StreamLogs(ctx context.Context, req *connect.Request[banyanpb.StreamLogsRequest]) (*connect.ServerStreamForClient[banyanpb.StreamLogsResponse], error) {
	return c.streamLogs.CallServerStream(ctx, req)
}

// AgentServiceHandler is an implementation of the banyan.v1.AgentService service.
type AgentServiceHandler interface {
	StreamLogs(context.Context, *connect.Request[banyanpb.StreamLogsRequest], *connect.ServerStream[banyanpb.StreamLogsResponse]) error
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := banyanpb.File_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceStreamLogsHandler := connect.NewServerStreamHandler(
		AgentServiceStreamLogsProcedure,
		svc.StreamLogs,
		connect.WithSchema(agentServiceMethods.ByName("StreamLogs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/banyan.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceStreamLogsProcedure:
			agentServiceStreamLogsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) StreamLogs(context.Context, *connect.Request[banyanpb.StreamLogsRequest], *connect.ServerStream[banyanpb.StreamLogsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.AgentService.StreamLogs is not implemented"))
}
