// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: engine.proto

package banyanpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	banyanpb "github.com/fertile-org/banyan/pkg/rpc/banyanpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EngineServiceName is the fully-qualified name of the EngineService service.
	EngineServiceName = "banyan.v1.EngineService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EngineServiceRegisterProcedure is the fully-qualified name of the EngineService's Register RPC.
	EngineServiceRegisterProcedure = "/banyan.v1.EngineService/Register"
	// EngineServiceHeartbeatProcedure is the fully-qualified name of the EngineService's Heartbeat RPC.
	EngineServiceHeartbeatProcedure = "/banyan.v1.EngineService/Heartbeat"
	// EngineServicePollTasksProcedure is the fully-qualified name of the EngineService's PollTasks RPC.
	EngineServicePollTasksProcedure = "/banyan.v1.EngineService/PollTasks"
	// EngineServiceReportTaskResultProcedure is the fully-qualified name of the EngineService's
	// ReportTaskResult RPC.
	EngineServiceReportTaskResultProcedure = "/banyan.v1.EngineService/ReportTaskResult"
	// EngineServiceReportContainerHealthProcedure is the fully-qualified name of the EngineService's
	// ReportContainerHealth RPC.
	EngineServiceReportContainerHealthProcedure = "/banyan.v1.EngineService/ReportContainerHealth"
	// EngineServiceDeployProcedure is the fully-qualified name of the EngineService's Deploy RPC.
	EngineServiceDeployProcedure = "/banyan.v1.EngineService/Deploy"
	// EngineServiceDownProcedure is the fully-qualified name of the EngineService's Down RPC.
	EngineServiceDownProcedure = "/banyan.v1.EngineService/Down"
	// EngineServiceGetStatusProcedure is the fully-qualified name of the EngineService's GetStatus RPC.
	EngineServiceGetStatusProcedure = "/banyan.v1.EngineService/GetStatus"
	// EngineServiceGetLogsProcedure is the fully-qualified name of the EngineService's GetLogs RPC.
	EngineServiceGetLogsProcedure = "/banyan.v1.EngineService/GetLogs"
	// EngineServiceGetInfoProcedure is the fully-qualified name of the EngineService's GetInfo RPC.
	EngineServiceGetInfoProcedure = "/banyan.v1.EngineService/GetInfo"
	// EngineServiceHealthProcedure is the fully-qualified name of the EngineService's Health RPC.
	EngineServiceHealthProcedure = "/banyan.v1.EngineService/Health"
	// EngineServiceScaleProcedure is the fully-qualified name of the EngineService's Scale RPC.
	EngineServiceScaleProcedure = "/banyan.v1.EngineService/Scale"
	// EngineServiceStopTaskProcedure is the fully-qualified name of the EngineService's StopTask RPC.
	EngineServiceStopTaskProcedure = "/banyan.v1.EngineService/StopTask"
	// EngineServiceGetDashboardDataProcedure is the fully-qualified name of the EngineService's
	// GetDashboardData RPC.
	EngineServiceGetDashboardDataProcedure = "/banyan.v1.EngineService/GetDashboardData"
	// EngineServiceGetClusterOverviewProcedure is the fully-qualified name of the EngineService's
	// GetClusterOverview RPC.
	EngineServiceGetClusterOverviewProcedure = "/banyan.v1.EngineService/GetClusterOverview"
	// EngineServiceListAgentsProcedure is the fully-qualified name of the EngineService's ListAgents
	// RPC.
	EngineServiceListAgentsProcedure = "/banyan.v1.EngineService/ListAgents"
	// EngineServiceListDeploymentsProcedure is the fully-qualified name of the EngineService's
	// ListDeployments RPC.
	EngineServiceListDeploymentsProcedure = "/banyan.v1.EngineService/ListDeployments"
	// EngineServiceGetDeploymentDetailProcedure is the fully-qualified name of the EngineService's
	// GetDeploymentDetail RPC.
	EngineServiceGetDeploymentDetailProcedure = "/banyan.v1.EngineService/GetDeploymentDetail"
	// EngineServiceListContainersProcedure is the fully-qualified name of the EngineService's
	// ListContainers RPC.
	EngineServiceListContainersProcedure = "/banyan.v1.EngineService/ListContainers"
	// EngineServiceListEventsProcedure is the fully-qualified name of the EngineService's ListEvents
	// RPC.
	EngineServiceListEventsProcedure = "/banyan.v1.EngineService/ListEvents"
	// EngineServiceGetRecentLogsProcedure is the fully-qualified name of the EngineService's
	// GetRecentLogs RPC.
	EngineServiceGetRecentLogsProcedure = "/banyan.v1.EngineService/GetRecentLogs"
	// EngineServiceCreateSecretProcedure is the fully-qualified name of the EngineService's
	// CreateSecret RPC.
	EngineServiceCreateSecretProcedure = "/banyan.v1.EngineService/CreateSecret"
	// EngineServiceListSecretsProcedure is the fully-qualified name of the EngineService's ListSecrets
	// RPC.
	EngineServiceListSecretsProcedure = "/banyan.v1.EngineService/ListSecrets"
	// EngineServiceGetSecretProcedure is the fully-qualified name of the EngineService's GetSecret RPC.
	EngineServiceGetSecretProcedure = "/banyan.v1.EngineService/GetSecret"
	// EngineServiceDeleteSecretProcedure is the fully-qualified name of the EngineService's
	// DeleteSecret RPC.
	EngineServiceDeleteSecretProcedure = "/banyan.v1.EngineService/DeleteSecret"
)

// EngineServiceClient is a client for the banyan.v1.EngineService service.
type EngineServiceClient interface {
	// Agent RPCs
	Register(context.Context, *connect.Request[banyanpb.RegisterRequest]) (*connect.Response[banyanpb.RegisterResponse], error)
	Heartbeat(context.Context, *connect.Request[banyanpb.HeartbeatRequest]) (*connect.Response[banyanpb.HeartbeatResponse], error)
	PollTasks(context.Context, *connect.Request[banyanpb.PollTasksRequest]) (*connect.Response[banyanpb.PollTasksResponse], error)
	ReportTaskResult(context.Context, *connect.Request[banyanpb.ReportTaskResultRequest]) (*connect.Response[banyanpb.ReportTaskResultResponse], error)
	ReportContainerHealth(context.Context, *connect.Request[banyanpb.ReportContainerHealthRequest]) (*connect.Response[banyanpb.ReportContainerHealthResponse], error)
	// CLI RPCs
	Deploy(context.Context, *connect.Request[banyanpb.DeployRPCRequest]) (*connect.Response[banyanpb.DeployRPCResponse], error)
	Down(context.Context, *connect.Request[banyanpb.DownRPCRequest]) (*connect.Response[banyanpb.DownRPCResponse], error)
	GetStatus(context.Context, *connect.Request[banyanpb.GetStatusRequest]) (*connect.Response[banyanpb.GetStatusResponse], error)
	GetLogs(context.Context, *connect.Request[banyanpb.GetLogsRequest]) (*connect.ServerStreamForClient[banyanpb.GetLogsResponse], error)
	GetInfo(context.Context, *connect.Request[banyanpb.GetInfoRequest]) (*connect.Response[banyanpb.GetInfoResponse], error)
	Health(context.Context, *connect.Request[banyanpb.HealthRequest]) (*connect.Response[banyanpb.HealthResponse], error)
	Scale(context.Context, *connect.Request[banyanpb.ScaleRequest]) (*connect.Response[banyanpb.ScaleResponse], error)
	// Operational RPCs (dashboard actions)
	StopTask(context.Context, *connect.Request[banyanpb.StopTaskRequest]) (*connect.Response[banyanpb.StopTaskResponse], error)
	// Dashboard RPCs (monolithic — used by CLI TUI)
	GetDashboardData(context.Context, *connect.Request[banyanpb.GetDashboardDataRequest]) (*connect.Response[banyanpb.GetDashboardDataResponse], error)
	// Web dashboard RPCs (per-page, lighter payloads)
	GetClusterOverview(context.Context, *connect.Request[banyanpb.GetClusterOverviewRequest]) (*connect.Response[banyanpb.GetClusterOverviewResponse], error)
	ListAgents(context.Context, *connect.Request[banyanpb.ListAgentsRequest]) (*connect.Response[banyanpb.ListAgentsResponse], error)
	ListDeployments(context.Context, *connect.Request[banyanpb.ListDeploymentsRequest]) (*connect.Response[banyanpb.ListDeploymentsResponse], error)
	GetDeploymentDetail(context.Context, *connect.Request[banyanpb.GetDeploymentDetailRequest]) (*connect.Response[banyanpb.GetDeploymentDetailResponse], error)
	ListContainers(context.Context, *connect.Request[banyanpb.ListContainersRequest]) (*connect.Response[banyanpb.ListContainersResponse], error)
	ListEvents(context.Context, *connect.Request[banyanpb.ListEventsRequest]) (*connect.Response[banyanpb.ListEventsResponse], error)
	GetRecentLogs(context.Context, *connect.Request[banyanpb.GetRecentLogsRequest]) (*connect.Response[banyanpb.GetRecentLogsResponse], error)
	// Secret RPCs
	CreateSecret(context.Context, *connect.Request[banyanpb.CreateSecretRequest]) (*connect.Response[banyanpb.CreateSecretResponse], error)
	ListSecrets(context.Context, *connect.Request[banyanpb.ListSecretsRequest]) (*connect.Response[banyanpb.ListSecretsResponse], error)
	GetSecret(context.Context, *connect.Request[banyanpb.GetSecretRequest]) (*connect.Response[banyanpb.GetSecretResponse], error)
	DeleteSecret(context.Context, *connect.Request[banyanpb.DeleteSecretRequest]) (*connect.Response[banyanpb.DeleteSecretResponse], error)
}

// NewEngineServiceClient constructs a client for the banyan.v1.EngineService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEngineServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EngineServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	engineServiceMethods := banyanpb.File_engine_proto.Services().ByName("EngineService").Methods()
	return &engineServiceClient{
		register: connect.NewClient[banyanpb.RegisterRequest, banyanpb.RegisterResponse](
			httpClient,
			baseURL+EngineServiceRegisterProcedure,
			connect.WithSchema(engineServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[banyanpb.HeartbeatRequest, banyanpb.HeartbeatResponse](
			httpClient,
			baseURL+EngineServiceHeartbeatProcedure,
			connect.WithSchema(engineServiceMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
		pollTasks: connect.NewClient[banyanpb.PollTasksRequest, banyanpb.PollTasksResponse](
			httpClient,
			baseURL+EngineServicePollTasksProcedure,
			connect.WithSchema(engineServiceMethods.ByName("PollTasks")),
			connect.WithClientOptions(opts...),
		),
		reportTaskResult: connect.NewClient[banyanpb.ReportTaskResultRequest, banyanpb.ReportTaskResultResponse](
			httpClient,
			baseURL+EngineServiceReportTaskResultProcedure,
			connect.WithSchema(engineServiceMethods.ByName("ReportTaskResult")),
			connect.WithClientOptions(opts...),
		),
		reportContainerHealth: connect.NewClient[banyanpb.ReportContainerHealthRequest, banyanpb.ReportContainerHealthResponse](
			httpClient,
			baseURL+EngineServiceReportContainerHealthProcedure,
			connect.WithSchema(engineServiceMethods.ByName("ReportContainerHealth")),
			connect.WithClientOptions(opts...),
		),
		deploy: connect.NewClient[banyanpb.DeployRPCRequest, banyanpb.DeployRPCResponse](
			httpClient,
			baseURL+EngineServiceDeployProcedure,
			connect.WithSchema(engineServiceMethods.ByName("Deploy")),
			connect.WithClientOptions(opts...),
		),
		down: connect.NewClient[banyanpb.DownRPCRequest, banyanpb.DownRPCResponse](
			httpClient,
			baseURL+EngineServiceDownProcedure,
			connect.WithSchema(engineServiceMethods.ByName("Down")),
			connect.WithClientOptions(opts...),
		),
		getStatus: connect.NewClient[banyanpb.GetStatusRequest, banyanpb.GetStatusResponse](
			httpClient,
			baseURL+EngineServiceGetStatusProcedure,
			connect.WithSchema(engineServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		getLogs: connect.NewClient[banyanpb.GetLogsRequest, banyanpb.GetLogsResponse](
			httpClient,
			baseURL+EngineServiceGetLogsProcedure,
			connect.WithSchema(engineServiceMethods.ByName("GetLogs")),
			connect.WithClientOptions(opts...),
		),
		getInfo: connect.NewClient[banyanpb.GetInfoRequest, banyanpb.GetInfoResponse](
			httpClient,
			baseURL+EngineServiceGetInfoProcedure,
			connect.WithSchema(engineServiceMethods.ByName("GetInfo")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[banyanpb.HealthRequest, banyanpb.HealthResponse](
			httpClient,
			baseURL+EngineServiceHealthProcedure,
			connect.WithSchema(engineServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		scale: connect.NewClient[banyanpb.ScaleRequest, banyanpb.ScaleResponse](
			httpClient,
			baseURL+EngineServiceScaleProcedure,
			connect.WithSchema(engineServiceMethods.ByName("Scale")),
			connect.WithClientOptions(opts...),
		),
		stopTask: connect.NewClient[banyanpb.StopTaskRequest, banyanpb.StopTaskResponse](
			httpClient,
			baseURL+EngineServiceStopTaskProcedure,
			connect.WithSchema(engineServiceMethods.ByName("StopTask")),
			connect.WithClientOptions(opts...),
		),
		getDashboardData: connect.NewClient[banyanpb.GetDashboardDataRequest, banyanpb.GetDashboardDataResponse](
			httpClient,
			baseURL+EngineServiceGetDashboardDataProcedure,
			connect.WithSchema(engineServiceMethods.ByName("GetDashboardData")),
			connect.WithClientOptions(opts...),
		),
		getClusterOverview: connect.NewClient[banyanpb.GetClusterOverviewRequest, banyanpb.GetClusterOverviewResponse](
			httpClient,
			baseURL+EngineServiceGetClusterOverviewProcedure,
			connect.WithSchema(engineServiceMethods.ByName("GetClusterOverview")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[banyanpb.ListAgentsRequest, banyanpb.ListAgentsResponse](
			httpClient,
			baseURL+EngineServiceListAgentsProcedure,
			connect.WithSchema(engineServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		listDeployments: connect.NewClient[banyanpb.ListDeploymentsRequest, banyanpb.ListDeploymentsResponse](
			httpClient,
			baseURL+EngineServiceListDeploymentsProcedure,
			connect.WithSchema(engineServiceMethods.ByName("ListDeployments")),
			connect.WithClientOptions(opts...),
		),
		getDeploymentDetail: connect.NewClient[banyanpb.GetDeploymentDetailRequest, banyanpb.GetDeploymentDetailResponse](
			httpClient,
			baseURL+EngineServiceGetDeploymentDetailProcedure,
			connect.WithSchema(engineServiceMethods.ByName("GetDeploymentDetail")),
			connect.WithClientOptions(opts...),
		),
		listContainers: connect.NewClient[banyanpb.ListContainersRequest, banyanpb.ListContainersResponse](
			httpClient,
			baseURL+EngineServiceListContainersProcedure,
			connect.WithSchema(engineServiceMethods.ByName("ListContainers")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[banyanpb.ListEventsRequest, banyanpb.ListEventsResponse](
			httpClient,
			baseURL+EngineServiceListEventsProcedure,
			connect.WithSchema(engineServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		getRecentLogs: connect.NewClient[banyanpb.GetRecentLogsRequest, banyanpb.GetRecentLogsResponse](
			httpClient,
			baseURL+EngineServiceGetRecentLogsProcedure,
			connect.WithSchema(engineServiceMethods.ByName("GetRecentLogs")),
			connect.WithClientOptions(opts...),
		),
		createSecret: connect.NewClient[banyanpb.CreateSecretRequest, banyanpb.CreateSecretResponse](
			httpClient,
			baseURL+EngineServiceCreateSecretProcedure,
			connect.WithSchema(engineServiceMethods.ByName("CreateSecret")),
			connect.WithClientOptions(opts...),
		),
		listSecrets: connect.NewClient[banyanpb.ListSecretsRequest, banyanpb.ListSecretsResponse](
			httpClient,
			baseURL+EngineServiceListSecretsProcedure,
			connect.WithSchema(engineServiceMethods.ByName("ListSecrets")),
			connect.WithClientOptions(opts...),
		),
		getSecret: connect.NewClient[banyanpb.GetSecretRequest, banyanpb.GetSecretResponse](
			httpClient,
			baseURL+EngineServiceGetSecretProcedure,
			connect.WithSchema(engineServiceMethods.ByName("GetSecret")),
			connect.WithClientOptions(opts...),
		),
		deleteSecret: connect.NewClient[banyanpb.DeleteSecretRequest, banyanpb.DeleteSecretResponse](
			httpClient,
			baseURL+EngineServiceDeleteSecretProcedure,
			connect.WithSchema(engineServiceMethods.ByName("DeleteSecret")),
			connect.WithClientOptions(opts...),
		),
	}
}

// engineServiceClient implements EngineServiceClient.
type engineServiceClient struct {
	register              *connect.Client[banyanpb.RegisterRequest, banyanpb.RegisterResponse]
	heartbeat             *connect.Client[banyanpb.HeartbeatRequest, banyanpb.HeartbeatResponse]
	pollTasks             *connect.Client[banyanpb.PollTasksRequest, banyanpb.PollTasksResponse]
	reportTaskResult      *connect.Client[banyanpb.ReportTaskResultRequest, banyanpb.ReportTaskResultResponse]
	reportContainerHealth *connect.Client[banyanpb.ReportContainerHealthRequest, banyanpb.ReportContainerHealthResponse]
	deploy                *connect.Client[banyanpb.DeployRPCRequest, banyanpb.DeployRPCResponse]
	down                  *connect.Client[banyanpb.DownRPCRequest, banyanpb.DownRPCResponse]
	getStatus             *connect.Client[banyanpb.GetStatusRequest, banyanpb.GetStatusResponse]
	getLogs               *connect.Client[banyanpb.GetLogsRequest, banyanpb.GetLogsResponse]
	getInfo               *connect.Client[banyanpb.GetInfoRequest, banyanpb.GetInfoResponse]
	health                *connect.Client[banyanpb.HealthRequest, banyanpb.HealthResponse]
	scale                 *connect.Client[banyanpb.ScaleRequest, banyanpb.ScaleResponse]
	stopTask              *connect.Client[banyanpb.StopTaskRequest, banyanpb.StopTaskResponse]
	getDashboardData      *connect.Client[banyanpb.GetDashboardDataRequest, banyanpb.GetDashboardDataResponse]
	getClusterOverview    *connect.Client[banyanpb.GetClusterOverviewRequest, banyanpb.GetClusterOverviewResponse]
	listAgents            *connect.Client[banyanpb.ListAgentsRequest, banyanpb.ListAgentsResponse]
	listDeployments       *connect.Client[banyanpb.ListDeploymentsRequest, banyanpb.ListDeploymentsResponse]
	getDeploymentDetail   *connect.Client[banyanpb.GetDeploymentDetailRequest, banyanpb.GetDeploymentDetailResponse]
	listContainers        *connect.Client[banyanpb.ListContainersRequest, banyanpb.ListContainersResponse]
	listEvents            *connect.Client[banyanpb.ListEventsRequest, banyanpb.ListEventsResponse]
	getRecentLogs         *connect.Client[banyanpb.GetRecentLogsRequest, banyanpb.GetRecentLogsResponse]
	createSecret          *connect.Client[banyanpb.CreateSecretRequest, banyanpb.CreateSecretResponse]
	listSecrets           *connect.Client[banyanpb.ListSecretsRequest, banyanpb.ListSecretsResponse]
	getSecret             *connect.Client[banyanpb.GetSecretRequest, banyanpb.GetSecretResponse]
	deleteSecret          *connect.Client[banyanpb.DeleteSecretRequest, banyanpb.DeleteSecretResponse]
}

// Register calls banyan.v1.EngineService.Register.
func (c *engineServiceClient) Register(ctx context.Context, req *connect.Request[banyanpb.RegisterRequest]) (*connect.Response[banyanpb.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Heartbeat calls banyan.v1.EngineService.Heartbeat.
func (c *engineServiceClient) Heartbeat(ctx context.Context, req *connect.Request[banyanpb.HeartbeatRequest]) (*connect.Response[banyanpb.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// PollTasks calls banyan.v1.EngineService.PollTasks.
func (c *engineServiceClient) PollTasks(ctx context.Context, req *connect.Request[banyanpb.PollTasksRequest]) (*connect.Response[banyanpb.PollTasksResponse], error) {
	return c.pollTasks.CallUnary(ctx, req)
}

// ReportTaskResult calls banyan.v1.EngineService.ReportTaskResult.
func (c *engineServiceClient) ReportTaskResult(ctx context.Context, req *connect.Request[banyanpb.ReportTaskResultRequest]) (*connect.Response[banyanpb.ReportTaskResultResponse], error) {
	return c.reportTaskResult.CallUnary(ctx, req)
}

// ReportContainerHealth calls banyan.v1.EngineService.ReportContainerHealth.
func (c *engineServiceClient) ReportContainerHealth(ctx context.Context, req *connect.Request[banyanpb.ReportContainerHealthRequest]) (*connect.Response[banyanpb.ReportContainerHealthResponse], error) {
	return c.reportContainerHealth.CallUnary(ctx, req)
}

// Deploy calls banyan.v1.EngineService.Deploy.
func (c *engineServiceClient) Deploy(ctx context.Context, req *connect.Request[banyanpb.DeployRPCRequest]) (*connect.Response[banyanpb.DeployRPCResponse], error) {
	return c.deploy.CallUnary(ctx, req)
}

// Down calls banyan.v1.EngineService.Down.
func (c *engineServiceClient) Down(ctx context.Context, req *connect.Request[banyanpb.DownRPCRequest]) (*connect.Response[banyanpb.DownRPCResponse], error) {
	return c.down.CallUnary(ctx, req)
}

// GetStatus calls banyan.v1.EngineService.GetStatus.
func (c *engineServiceClient) GetStatus(ctx context.Context, req *connect.Request[banyanpb.GetStatusRequest]) (*connect.Response[banyanpb.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// GetLogs calls banyan.v1.EngineService.GetLogs.
func (c *engineServiceClient) GetLogs(ctx context.Context, req *connect.Request[banyanpb.GetLogsRequest]) (*connect.ServerStreamForClient[banyanpb.GetLogsResponse], error) {
	return c.getLogs.CallServerStream(ctx, req)
}

// GetInfo calls banyan.v1.EngineService.GetInfo.
func (c *engineServiceClient) GetInfo(ctx context.Context, req *connect.Request[banyanpb.GetInfoRequest]) (*connect.Response[banyanpb.GetInfoResponse], error) {
	return c.getInfo.CallUnary(ctx, req)
}

// Health calls banyan.v1.EngineService.Health.
func (c *engineServiceClient) Health(ctx context.Context, req *connect.Request[banyanpb.HealthRequest]) (*connect.Response[banyanpb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// Scale calls banyan.v1.EngineService.Scale.
func (c *engineServiceClient) Scale(ctx context.Context, req *connect.Request[banyanpb.ScaleRequest]) (*connect.Response[banyanpb.ScaleResponse], error) {
	return c.scale.CallUnary(ctx, req)
}

// StopTask calls banyan.v1.EngineService.StopTask.
func (c *engineServiceClient) StopTask(ctx context.Context, req *connect.Request[banyanpb.StopTaskRequest]) (*connect.Response[banyanpb.StopTaskResponse], error) {
	return c.stopTask.CallUnary(ctx, req)
}

// GetDashboardData calls banyan.v1.EngineService.GetDashboardData.
func (c *engineServiceClient) GetDashboardData(ctx context.Context, req *connect.Request[banyanpb.GetDashboardDataRequest]) (*connect.Response[banyanpb.GetDashboardDataResponse], error) {
	return c.getDashboardData.CallUnary(ctx, req)
}

// GetClusterOverview calls banyan.v1.EngineService.GetClusterOverview.
func (c *engineServiceClient) GetClusterOverview(ctx context.Context, req *connect.Request[banyanpb.GetClusterOverviewRequest]) (*connect.Response[banyanpb.GetClusterOverviewResponse], error) {
	return c.getClusterOverview.CallUnary(ctx, req)
}

// ListAgents calls banyan.v1.EngineService.ListAgents.
func (c *engineServiceClient) ListAgents(ctx context.Context, req *connect.Request[banyanpb.ListAgentsRequest]) (*connect.Response[banyanpb.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// ListDeployments calls banyan.v1.EngineService.ListDeployments.
func (c *engineServiceClient) ListDeployments(ctx context.Context, req *connect.Request[banyanpb.ListDeploymentsRequest]) (*connect.Response[banyanpb.ListDeploymentsResponse], error) {
	return c.listDeployments.CallUnary(ctx, req)
}

// GetDeploymentDetail calls banyan.v1.EngineService.GetDeploymentDetail.
func (c *engineServiceClient) GetDeploymentDetail(ctx context.Context, req *connect.Request[banyanpb.GetDeploymentDetailRequest]) (*connect.Response[banyanpb.GetDeploymentDetailResponse], error) {
	return c.getDeploymentDetail.CallUnary(ctx, req)
}

// ListContainers calls banyan.v1.EngineService.ListContainers.
func (c *engineServiceClient) ListContainers(ctx context.Context, req *connect.Request[banyanpb.ListContainersRequest]) (*connect.Response[banyanpb.ListContainersResponse], error) {
	return c.listContainers.CallUnary(ctx, req)
}

// ListEvents calls banyan.v1.EngineService.ListEvents.
func (c *engineServiceClient) ListEvents(ctx context.Context, req *connect.Request[banyanpb.ListEventsRequest]) (*connect.Response[banyanpb.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// GetRecentLogs calls banyan.v1.EngineService.GetRecentLogs.
func (c *engineServiceClient) GetRecentLogs(ctx context.Context, req *connect.Request[banyanpb.GetRecentLogsRequest]) (*connect.Response[banyanpb.GetRecentLogsResponse], error) {
	return c.getRecentLogs.CallUnary(ctx, req)
}

// CreateSecret calls banyan.v1.EngineService.CreateSecret.
func (c *engineServiceClient) CreateSecret(ctx context.Context, req *connect.Request[banyanpb.CreateSecretRequest]) (*connect.Response[banyanpb.CreateSecretResponse], error) {
	return c.createSecret.CallUnary(ctx, req)
}

// ListSecrets calls banyan.v1.EngineService.ListSecrets.
func (c *engineServiceClient) ListSecrets(ctx context.Context, req *connect.Request[banyanpb.ListSecretsRequest]) (*connect.Response[banyanpb.ListSecretsResponse], error) {
	return c.listSecrets.CallUnary(ctx, req)
}

// GetSecret calls banyan.v1.EngineService.GetSecret.
func (c *engineServiceClient) GetSecret(ctx context.Context, req *connect.Request[banyanpb.GetSecretRequest]) (*connect.Response[banyanpb.GetSecretResponse], error) {
	return c.getSecret.CallUnary(ctx, req)
}

// DeleteSecret calls banyan.v1.EngineService.DeleteSecret.
func (c *engineServiceClient) DeleteSecret(ctx context.Context, req *connect.Request[banyanpb.DeleteSecretRequest]) (*connect.Response[banyanpb.DeleteSecretResponse], error) {
	return c.deleteSecret.CallUnary(ctx, req)
}

// EngineServiceHandler is an implementation of the banyan.v1.EngineService service.
type EngineServiceHandler interface {
	// Agent RPCs
	Register(context.Context, *connect.Request[banyanpb.RegisterRequest]) (*connect.Response[banyanpb.RegisterResponse], error)
	Heartbeat(context.Context, *connect.Request[banyanpb.HeartbeatRequest]) (*connect.Response[banyanpb.HeartbeatResponse], error)
	PollTasks(context.Context, *connect.Request[banyanpb.PollTasksRequest]) (*connect.Response[banyanpb.PollTasksResponse], error)
	ReportTaskResult(context.Context, *connect.Request[banyanpb.ReportTaskResultRequest]) (*connect.Response[banyanpb.ReportTaskResultResponse], error)
	ReportContainerHealth(context.Context, *connect.Request[banyanpb.ReportContainerHealthRequest]) (*connect.Response[banyanpb.ReportContainerHealthResponse], error)
	// CLI RPCs
	Deploy(context.Context, *connect.Request[banyanpb.DeployRPCRequest]) (*connect.Response[banyanpb.DeployRPCResponse], error)
	Down(context.Context, *connect.Request[banyanpb.DownRPCRequest]) (*connect.Response[banyanpb.DownRPCResponse], error)
	GetStatus(context.Context, *connect.Request[banyanpb.GetStatusRequest]) (*connect.Response[banyanpb.GetStatusResponse], error)
	GetLogs(context.Context, *connect.Request[banyanpb.GetLogsRequest], *connect.ServerStream[banyanpb.GetLogsResponse]) error
	GetInfo(context.Context, *connect.Request[banyanpb.GetInfoRequest]) (*connect.Response[banyanpb.GetInfoResponse], error)
	Health(context.Context, *connect.Request[banyanpb.HealthRequest]) (*connect.Response[banyanpb.HealthResponse], error)
	Scale(context.Context, *connect.Request[banyanpb.ScaleRequest]) (*connect.Response[banyanpb.ScaleResponse], error)
	// Operational RPCs (dashboard actions)
	StopTask(context.Context, *connect.Request[banyanpb.StopTaskRequest]) (*connect.Response[banyanpb.StopTaskResponse], error)
	// Dashboard RPCs (monolithic — used by CLI TUI)
	GetDashboardData(context.Context, *connect.Request[banyanpb.GetDashboardDataRequest]) (*connect.Response[banyanpb.GetDashboardDataResponse], error)
	// Web dashboard RPCs (per-page, lighter payloads)
	GetClusterOverview(context.Context, *connect.Request[banyanpb.GetClusterOverviewRequest]) (*connect.Response[banyanpb.GetClusterOverviewResponse], error)
	ListAgents(context.Context, *connect.Request[banyanpb.ListAgentsRequest]) (*connect.Response[banyanpb.ListAgentsResponse], error)
	ListDeployments(context.Context, *connect.Request[banyanpb.ListDeploymentsRequest]) (*connect.Response[banyanpb.ListDeploymentsResponse], error)
	GetDeploymentDetail(context.Context, *connect.Request[banyanpb.GetDeploymentDetailRequest]) (*connect.Response[banyanpb.GetDeploymentDetailResponse], error)
	ListContainers(context.Context, *connect.Request[banyanpb.ListContainersRequest]) (*connect.Response[banyanpb.ListContainersResponse], error)
	ListEvents(context.Context, *connect.Request[banyanpb.ListEventsRequest]) (*connect.Response[banyanpb.ListEventsResponse], error)
	GetRecentLogs(context.Context, *connect.Request[banyanpb.GetRecentLogsRequest]) (*connect.Response[banyanpb.GetRecentLogsResponse], error)
	// Secret RPCs
	CreateSecret(context.Context, *connect.Request[banyanpb.CreateSecretRequest]) (*connect.Response[banyanpb.CreateSecretResponse], error)
	ListSecrets(context.Context, *connect.Request[banyanpb.ListSecretsRequest]) (*connect.Response[banyanpb.ListSecretsResponse], error)
	GetSecret(context.Context, *connect.Request[banyanpb.GetSecretRequest]) (*connect.Response[banyanpb.GetSecretResponse], error)
	DeleteSecret(context.Context, *connect.Request[banyanpb.DeleteSecretRequest]) (*connect.Response[banyanpb.DeleteSecretResponse], error)
}

// NewEngineServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEngineServiceHandler(svc EngineServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	engineServiceMethods := banyanpb.File_engine_proto.Services().ByName("EngineService").Methods()
	engineServiceRegisterHandler := connect.NewUnaryHandler(
		EngineServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(engineServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceHeartbeatHandler := connect.NewUnaryHandler(
		EngineServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(engineServiceMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	engineServicePollTasksHandler := connect.NewUnaryHandler(
		EngineServicePollTasksProcedure,
		svc.PollTasks,
		connect.WithSchema(engineServiceMethods.ByName("PollTasks")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceReportTaskResultHandler := connect.NewUnaryHandler(
		EngineServiceReportTaskResultProcedure,
		svc.ReportTaskResult,
		connect.WithSchema(engineServiceMethods.ByName("ReportTaskResult")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceReportContainerHealthHandler := connect.NewUnaryHandler(
		EngineServiceReportContainerHealthProcedure,
		svc.ReportContainerHealth,
		connect.WithSchema(engineServiceMethods.ByName("ReportContainerHealth")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceDeployHandler := connect.NewUnaryHandler(
		EngineServiceDeployProcedure,
		svc.Deploy,
		connect.WithSchema(engineServiceMethods.ByName("Deploy")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceDownHandler := connect.NewUnaryHandler(
		EngineServiceDownProcedure,
		svc.Down,
		connect.WithSchema(engineServiceMethods.ByName("Down")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceGetStatusHandler := connect.NewUnaryHandler(
		EngineServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(engineServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceGetLogsHandler := connect.NewServerStreamHandler(
		EngineServiceGetLogsProcedure,
		svc.GetLogs,
		connect.WithSchema(engineServiceMethods.ByName("GetLogs")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceGetInfoHandler := connect.NewUnaryHandler(
		EngineServiceGetInfoProcedure,
		svc.GetInfo,
		connect.WithSchema(engineServiceMethods.ByName("GetInfo")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceHealthHandler := connect.NewUnaryHandler(
		EngineServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(engineServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceScaleHandler := connect.NewUnaryHandler(
		EngineServiceScaleProcedure,
		svc.Scale,
		connect.WithSchema(engineServiceMethods.ByName("Scale")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceStopTaskHandler := connect.NewUnaryHandler(
		EngineServiceStopTaskProcedure,
		svc.StopTask,
		connect.WithSchema(engineServiceMethods.ByName("StopTask")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceGetDashboardDataHandler := connect.NewUnaryHandler(
		EngineServiceGetDashboardDataProcedure,
		svc.GetDashboardData,
		connect.WithSchema(engineServiceMethods.ByName("GetDashboardData")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceGetClusterOverviewHandler := connect.NewUnaryHandler(
		EngineServiceGetClusterOverviewProcedure,
		svc.GetClusterOverview,
		connect.WithSchema(engineServiceMethods.ByName("GetClusterOverview")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceListAgentsHandler := connect.NewUnaryHandler(
		EngineServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(engineServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceListDeploymentsHandler := connect.NewUnaryHandler(
		EngineServiceListDeploymentsProcedure,
		svc.ListDeployments,
		connect.WithSchema(engineServiceMethods.ByName("ListDeployments")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceGetDeploymentDetailHandler := connect.NewUnaryHandler(
		EngineServiceGetDeploymentDetailProcedure,
		svc.GetDeploymentDetail,
		connect.WithSchema(engineServiceMethods.ByName("GetDeploymentDetail")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceListContainersHandler := connect.NewUnaryHandler(
		EngineServiceListContainersProcedure,
		svc.ListContainers,
		connect.WithSchema(engineServiceMethods.ByName("ListContainers")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceListEventsHandler := connect.NewUnaryHandler(
		EngineServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(engineServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceGetRecentLogsHandler := connect.NewUnaryHandler(
		EngineServiceGetRecentLogsProcedure,
		svc.GetRecentLogs,
		connect.WithSchema(engineServiceMethods.ByName("GetRecentLogs")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceCreateSecretHandler := connect.NewUnaryHandler(
		EngineServiceCreateSecretProcedure,
		svc.CreateSecret,
		connect.WithSchema(engineServiceMethods.ByName("CreateSecret")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceListSecretsHandler := connect.NewUnaryHandler(
		EngineServiceListSecretsProcedure,
		svc.ListSecrets,
		connect.WithSchema(engineServiceMethods.ByName("ListSecrets")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceGetSecretHandler := connect.NewUnaryHandler(
		EngineServiceGetSecretProcedure,
		svc.GetSecret,
		connect.WithSchema(engineServiceMethods.ByName("GetSecret")),
		connect.WithHandlerOptions(opts...),
	)
	engineServiceDeleteSecretHandler := connect.NewUnaryHandler(
		EngineServiceDeleteSecretProcedure,
		svc.DeleteSecret,
		connect.WithSchema(engineServiceMethods.ByName("DeleteSecret")),
		connect.WithHandlerOptions(opts...),
	)
	return "/banyan.v1.EngineService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EngineServiceRegisterProcedure:
			engineServiceRegisterHandler.ServeHTTP(w, r)
		case EngineServiceHeartbeatProcedure:
			engineServiceHeartbeatHandler.ServeHTTP(w, r)
		case EngineServicePollTasksProcedure:
			engineServicePollTasksHandler.ServeHTTP(w, r)
		case EngineServiceReportTaskResultProcedure:
			engineServiceReportTaskResultHandler.ServeHTTP(w, r)
		case EngineServiceReportContainerHealthProcedure:
			engineServiceReportContainerHealthHandler.ServeHTTP(w, r)
		case EngineServiceDeployProcedure:
			engineServiceDeployHandler.ServeHTTP(w, r)
		case EngineServiceDownProcedure:
			engineServiceDownHandler.ServeHTTP(w, r)
		case EngineServiceGetStatusProcedure:
			engineServiceGetStatusHandler.ServeHTTP(w, r)
		case EngineServiceGetLogsProcedure:
			engineServiceGetLogsHandler.ServeHTTP(w, r)
		case EngineServiceGetInfoProcedure:
			engineServiceGetInfoHandler.ServeHTTP(w, r)
		case EngineServiceHealthProcedure:
			engineServiceHealthHandler.ServeHTTP(w, r)
		case EngineServiceScaleProcedure:
			engineServiceScaleHandler.ServeHTTP(w, r)
		case EngineServiceStopTaskProcedure:
			engineServiceStopTaskHandler.ServeHTTP(w, r)
		case EngineServiceGetDashboardDataProcedure:
			engineServiceGetDashboardDataHandler.ServeHTTP(w, r)
		case EngineServiceGetClusterOverviewProcedure:
			engineServiceGetClusterOverviewHandler.ServeHTTP(w, r)
		case EngineServiceListAgentsProcedure:
			engineServiceListAgentsHandler.ServeHTTP(w, r)
		case EngineServiceListDeploymentsProcedure:
			engineServiceListDeploymentsHandler.ServeHTTP(w, r)
		case EngineServiceGetDeploymentDetailProcedure:
			engineServiceGetDeploymentDetailHandler.ServeHTTP(w, r)
		case EngineServiceListContainersProcedure:
			engineServiceListContainersHandler.ServeHTTP(w, r)
		case EngineServiceListEventsProcedure:
			engineServiceListEventsHandler.ServeHTTP(w, r)
		case EngineServiceGetRecentLogsProcedure:
			engineServiceGetRecentLogsHandler.ServeHTTP(w, r)
		case EngineServiceCreateSecretProcedure:
			engineServiceCreateSecretHandler.ServeHTTP(w, r)
		case EngineServiceListSecretsProcedure:
			engineServiceListSecretsHandler.ServeHTTP(w, r)
		case EngineServiceGetSecretProcedure:
			engineServiceGetSecretHandler.ServeHTTP(w, r)
		case EngineServiceDeleteSecretProcedure:
			engineServiceDeleteSecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEngineServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEngineServiceHandler struct{}

func (UnimplementedEngineServiceHandler) Register(context.Context, *connect.Request[banyanpb.RegisterRequest]) (*connect.Response[banyanpb.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.Register is not implemented"))
}

func (UnimplementedEngineServiceHandler) Heartbeat(context.Context, *connect.Request[banyanpb.HeartbeatRequest]) (*connect.Response[banyanpb.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.Heartbeat is not implemented"))
}

func (UnimplementedEngineServiceHandler) PollTasks(context.Context, *connect.Request[banyanpb.PollTasksRequest]) (*connect.Response[banyanpb.PollTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.PollTasks is not implemented"))
}

func (UnimplementedEngineServiceHandler) ReportTaskResult(context.Context, *connect.Request[banyanpb.ReportTaskResultRequest]) (*connect.Response[banyanpb.ReportTaskResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.ReportTaskResult is not implemented"))
}

func (UnimplementedEngineServiceHandler) ReportContainerHealth(context.Context, *connect.Request[banyanpb.ReportContainerHealthRequest]) (*connect.Response[banyanpb.ReportContainerHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.ReportContainerHealth is not implemented"))
}

func (UnimplementedEngineServiceHandler) Deploy(context.Context, *connect.Request[banyanpb.DeployRPCRequest]) (*connect.Response[banyanpb.DeployRPCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.Deploy is not implemented"))
}

func (UnimplementedEngineServiceHandler) Down(context.Context, *connect.Request[banyanpb.DownRPCRequest]) (*connect.Response[banyanpb.DownRPCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.Down is not implemented"))
}

func (UnimplementedEngineServiceHandler) GetStatus(context.Context, *connect.Request[banyanpb.GetStatusRequest]) (*connect.Response[banyanpb.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.GetStatus is not implemented"))
}

func (UnimplementedEngineServiceHandler) GetLogs(context.Context, *connect.Request[banyanpb.GetLogsRequest], *connect.ServerStream[banyanpb.GetLogsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.GetLogs is not implemented"))
}

func (UnimplementedEngineServiceHandler) GetInfo(context.Context, *connect.Request[banyanpb.GetInfoRequest]) (*connect.Response[banyanpb.GetInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.GetInfo is not implemented"))
}

func (UnimplementedEngineServiceHandler) Health(context.Context, *connect.Request[banyanpb.HealthRequest]) (*connect.Response[banyanpb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.Health is not implemented"))
}

func (UnimplementedEngineServiceHandler) Scale(context.Context, *connect.Request[banyanpb.ScaleRequest]) (*connect.Response[banyanpb.ScaleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.Scale is not implemented"))
}

func (UnimplementedEngineServiceHandler) StopTask(context.Context, *connect.Request[banyanpb.StopTaskRequest]) (*connect.Response[banyanpb.StopTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.StopTask is not implemented"))
}

func (UnimplementedEngineServiceHandler) GetDashboardData(context.Context, *connect.Request[banyanpb.GetDashboardDataRequest]) (*connect.Response[banyanpb.GetDashboardDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.GetDashboardData is not implemented"))
}

func (UnimplementedEngineServiceHandler) GetClusterOverview(context.Context, *connect.Request[banyanpb.GetClusterOverviewRequest]) (*connect.Response[banyanpb.GetClusterOverviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.GetClusterOverview is not implemented"))
}

func (UnimplementedEngineServiceHandler) ListAgents(context.Context, *connect.Request[banyanpb.ListAgentsRequest]) (*connect.Response[banyanpb.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.ListAgents is not implemented"))
}

func (UnimplementedEngineServiceHandler) ListDeployments(context.Context, *connect.Request[banyanpb.ListDeploymentsRequest]) (*connect.Response[banyanpb.ListDeploymentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.ListDeployments is not implemented"))
}

func (UnimplementedEngineServiceHandler) GetDeploymentDetail(context.Context, *connect.Request[banyanpb.GetDeploymentDetailRequest]) (*connect.Response[banyanpb.GetDeploymentDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.GetDeploymentDetail is not implemented"))
}

func (UnimplementedEngineServiceHandler) ListContainers(context.Context, *connect.Request[banyanpb.ListContainersRequest]) (*connect.Response[banyanpb.ListContainersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.ListContainers is not implemented"))
}

func (UnimplementedEngineServiceHandler) ListEvents(context.Context, *connect.Request[banyanpb.ListEventsRequest]) (*connect.Response[banyanpb.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.ListEvents is not implemented"))
}

func (UnimplementedEngineServiceHandler) GetRecentLogs(context.Context, *connect.Request[banyanpb.GetRecentLogsRequest]) (*connect.Response[banyanpb.GetRecentLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.GetRecentLogs is not implemented"))
}

func (UnimplementedEngineServiceHandler) CreateSecret(context.Context, *connect.Request[banyanpb.CreateSecretRequest]) (*connect.Response[banyanpb.CreateSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.CreateSecret is not implemented"))
}

func (UnimplementedEngineServiceHandler) ListSecrets(context.Context, *connect.Request[banyanpb.ListSecretsRequest]) (*connect.Response[banyanpb.ListSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.ListSecrets is not implemented"))
}

func (UnimplementedEngineServiceHandler) GetSecret(context.Context, *connect.Request[banyanpb.GetSecretRequest]) (*connect.Response[banyanpb.GetSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.GetSecret is not implemented"))
}

func (UnimplementedEngineServiceHandler) DeleteSecret(context.Context, *connect.Request[banyanpb.DeleteSecretRequest]) (*connect.Response[banyanpb.DeleteSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("banyan.v1.EngineService.DeleteSecret is not implemented"))
}
